export type RootStackParamList = {
  Welcome: undefined;
  Login: undefined;
  Register: undefined;
  ResetPassword: undefined;
  Home: undefined;
  Market: undefined;
  Portfolio: undefined;
  Profile: undefined;
  Screening: undefined;
  Create: undefined;
  StockDetail: { symbol: string };
  Security: undefined;
  Experience: undefined;
  NewsDetail: undefined;
  Success: undefined;
  OTP: undefined;
  NewPassword: undefined;
  PasswordChanged: undefined;
  NotificationPermission: undefined;
  PrivacyScreen: undefined;
  ForgotPassword: undefined;
  OTPVerification: { email: string };
  Main: undefined;
  KYC: undefined;
  KYCSuccess: undefined;
  BankVerification: undefined;
  BankConfirmation: undefined;
  SelfieVerification: undefined;
  SelfiePreview: { imageUri: string };
  SignatureScreen: undefined;
  SignatureDrawing: undefined;
  PersonalDetailsScreen: undefined;
  SignatureDrawingScreen: undefined;
  EmploymentDetailsScreen: undefined;
  AdditionalDetailsScreen: undefined;
  Watchlist: undefined;
  Order: { symbol: string; type: 'buy' | 'sell' };
  TransactionHistory: undefined;
  TransactionDetail: { transactionId: string };
  Settings: undefined;
  StockDetails: { symbol: string };
  HotNews:undefined;
  Search:undefined;
  PersonalInformationScreen:undefined;
  StockDetailScreen:{symbol:string};
  SearchScreen:undefined;
  AdvancedChartScreen: { symbol: string; companyName?: string };
  IndexDetailScreen:{symbol:string};
  MainAppTabs: undefined;
  ExchangeScreen:undefined;
};
